project_id: "630498"
api_token_env: CROWDIN_PERSONAL_TOKEN
api_token: 'MY-TOKEN'
preserve_hierarchy: true
files:
  # JSON 翻译文件
  - source: /i18n/zh-Hans/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Markdown 文档文件
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
